### ISSUE TITLE
Can't it run on windows?

### ISSUE THREAD

**Issue by aleffsouza** [senecajs/ramanujan#23]
I ran every command to start the applications btw for every service I've got this error:

```
running:  set PROXY_HOST=127.0.0.1&&set SERVICE_HOST=0.0.0.0&&set base0_PORT=10000&&set base1_PORT=10001&&set front_PORT=10002&&set api_PORT=10003&&set post_PORT=10004&&set entry_store_PORT=10005&&set entry_cache_PORT=10006&&set repl_PORT=10007&&set mine_PORT=10008&&set home_PORT=10009&&set index_PORT=10010&&set search_PORT=10011&&set follow_PORT=10012&&set fanout_PORT=10013&&set timeline0_PORT=10014&&set timeline1_PORT=10015&&set timeline_shard_PORT=10016&&set reserve_PORT=10017&&set SERVICE_PORT=20014&& 

"C:\Program Files\nodejs\node.exe" -r 

"...\AppData\Roaming\npm\node_modules\fuge\fuge.js" timeline-service.js 0 127.0.0.1:39000,127.0.0.1:39001 --seneca.options.debug.undead=true --seneca.options.plugin.mesh.sneeze.silent=1
[search - 6376]: module.js:568
[search - 6376]:   return process.dlopen(module, path._makeLong(filename));
[search - 6376]:                  ^
[search - 6376]:
[search - 6376]: Error: %1 It isn't a valid Win32 application.
[search - 6376]: \\?\C:\...\ramanujan\node_modules\farmhash\build\Release\farmhash.node
[search - 6376]:     at Error (native)
[search - 6376]:     at Object.Module._extensions..node (module.js:568:18)
[search - 6376]:     at Module.load (module.js:458:32)
[search - 6376]:     at tryModuleLoad (module.js:417:12)
[search - 6376]:     at Function.Module._load (module.js:409:3)
[search - 6376]:     at Module.require (module.js:468:17)
[search - 6376]:     at require (internal/module.js:20:19)
[search - 6376]:     at Object.<anonymous> (C:\...\ramanujan\node_modules\farmhash\index.js:4:16)
[search - 6376]:     at Module._compile (module.js:541:32)
[search - 6376]:     at Object.Module._extensions..js (module.js:550:10)
```

**Comment by aleffsouza** [comment]
I figured out I was using node 6 x64 and for some reason something use a x32 dll, I just installed a x32 version of Node 7 and it's almost working but now the front service has  restarted all the time and I can't start the application anyway... 

```
running: front
running:  set PROXY_HOST=127.0.0.1&&set SERVICE_HOST=0.0.0.0&&set base0_PORT=10000&&set base1_PORT=10001&&set front_PORT=10002&&set api_PORT=10003&&set post
_PORT=10004&&set entry_store_PORT=10005&&set entry_cache_PORT=10006&&set repl_PORT=10007&&set mine_PORT=10008&&set home_PORT=10009&&set index_PORT=10010&&se
t search_PORT=10011&&set follow_PORT=10012&&set fanout_PORT=10013&&set timeline0_PORT=10014&&set timeline1_PORT=10015&&set timeline_shard_PORT=10016&&set re
serve_PORT=10017&&set SERVICE_PORT=20002&& "C:\Program Files (x86)\nodejs\node.exe" -r "C:\...\AppData\Roaming\npm\node_modules\fuge\fuge.js" front.
js 127.0.0.1:39000,127.0.0.1:39001 --seneca.options.debug.undead=true --seneca.options.plugin.mesh.sneeze.silent=1
[front - 13500]: (node:20064) DeprecationWarning: os.tmpDir() is `deprecated.` Use os.tmpdir() instead.
[front - 13500]: front http://localhost:8000
process exit [13500]: front
process terminated unexpectedly [13500]: front restarting
```

Also There are some possible memory leaks warnings at start of the services:

```
(node:23572) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to in
crease limit
(node:23572) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added. Use emitter.setMaxListeners() to increase l
imit
(node:23572) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase li
mit
(node:23572) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase li
mit
(node:23572) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase li
mit
```
