### ISSUE TITLE
error npm install

### ISSUE THREAD

**Issue by luongquocdinh** [senecajs/ramanujan#4]
npm install when I made the error like this:

npm WARN engine wo@0.7.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.25","npm":"2.15.6"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"2.15.6"})
npm WARN engine wreck@6.3.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"2.15.6"})
npm WARN engine joi@6.10.1: wanted: {"node":">=0.10.40","npm":">=2.0.0"} (current: {"node":"0.10.25","npm":"2.15.6"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"2.15.6"})
npm WARN engine topo@1.1.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"2.15.6"})
npm WARN engine msgpack@1.0.2: wanted: {"node":">=0.12.7"} (current: {"node":"0.10.25","npm":"2.15.6"})
npm WARN engine wreck@6.3.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"2.15.6"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"2.15.6"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"2.15.6"})

> farmhash@1.1.1 install /home/quocdinh/Git/ramanujan/node_modules/sneeze/node_modules/swim/node_modules/farmhash
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.25"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/quocdinh/Git/ramanujan/node_modules/sneeze/node_modules/swim/node_modules/farmhash/.node-gyp"
make: Entering directory `/home/quocdinh/Git/ramanujan/node_modules/sneeze/node_modules/swim/node_modules/farmhash/build'
  CXX(target) Release/obj.target/farmhash/src/upstream/farmhash.o
  CXX(target) Release/obj.target/farmhash/src/bindings.o
  SOLINK_MODULE(target) Release/obj.target/farmhash.node
  COPY Release/farmhash.node
make: Leaving directory`/home/quocdinh/Git/ramanujan/node_modules/sneeze/node_modules/swim/node_modules/farmhash/build'

> msgpack@1.0.2 install /home/quocdinh/Git/ramanujan/node_modules/sneeze/node_modules/swim/node_modules/msgpack
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.25"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/quocdinh/Git/ramanujan/node_modules/sneeze/node_modules/swim/node_modules/msgpack/.node-gyp"
make: Entering directory `/home/quocdinh/Git/ramanujan/node_modules/sneeze/node_modules/swim/node_modules/msgpack/build'
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/objectc.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/unpack.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/vrefbuffer.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/zone.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/version.o
  AR(target) Release/obj.target/deps/msgpack/msgpack.a
  COPY Release/msgpack.a
  CXX(target) Release/obj.target/msgpackBinding/src/msgpack.o
../src/msgpack.cc: In function ‘void v8_to_msgpack(v8::Handle<v8::Value>, msgpack_object*, msgpack_zone*, size_t)’:
../src/msgpack.cc:126:93: error: could not convert ‘v8obj’ from ‘v8::Handle<v8::Value>’ to ‘v8::Local<v8::Value>’
         mo->via.str.size = static_cast<uint32_t>(Nan::DecodeBytes(v8obj, Nan::Encoding::UTF8));
                                                                                             ^
../src/msgpack.cc:129:94: error: could not convert ‘v8obj’ from ‘v8::Handle<v8::Value>’ to ‘v8::Local<v8::Value>’
         Nan::DecodeWrite((char*)mo->via.str.ptr, mo->via.str.size, v8obj, Nan::Encoding::UTF8);
                                                                                              ^
../src/msgpack.cc:136:94: error: could not convert ‘result’ from ‘v8::Handle<v8::Value>’ to ‘v8::Local<v8::Value>’
         mo->via.str.size = static_cast<uint32_t>(Nan::DecodeBytes(result, Nan::Encoding::UTF8));
                                                                                              ^
../src/msgpack.cc:139:95: error: could not convert ‘result’ from ‘v8::Handle<v8::Value>’ to ‘v8::Local<v8::Value>’
         Nan::DecodeWrite((char*)mo->via.str.ptr, mo->via.str.size, result, Nan::Encoding::UTF8);
                                                                                               ^
make: *** [Release/obj.target/msgpackBinding/src/msgpack.o] Error 1
make: Leaving directory`/home/quocdinh/Git/ramanujan/node_modules/sneeze/node_modules/swim/node_modules/msgpack/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.19.0-59-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/quocdinh/Git/ramanujan/node_modules/sneeze/node_modules/swim/node_modules/msgpack
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 3.19.0-59-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.25
npm ERR! npm  v2.15.6
npm ERR! code ELIFECYCLE

npm ERR! msgpack@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the msgpack@1.0.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the msgpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs msgpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls msgpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/quocdinh/Git/ramanujan/npm-debug.log

**Comment by davidmarkclements** [comment]
hi @luongquocdinh looks like the msgpack dep is failing - what version of Node are you running, and what's your OS? 

msgpack does seem to have build issues on recent node versions, see https://github.com/msgpack/msgpack-node/issues/33 and https://github.com/msgpack/msgpack-node/issues/31

**Comment by luongquocdinh** [comment]
I use node v0.10.25 and ubuntu 14.04

**Comment by kevin-madhu** [comment]
If I'm not wrong that version of node should be very very old. I'm using node v4.4.1 and everything is fine. It's better to use nvm and install a new version of node.

**Comment by lfurzewaddock** [comment]
@luongquocdinh Have you checked python? See issue #29
